CREATE TABLE TB_DEPARTMENT
(
    DEPARTMENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(20) NOT NULL,
    CATEGORY VARCHAR2(20),
    OPEN_YN CHAR(1),
    CAPACITY NUMBER
);
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NO IS '학과번호';
COMMENT ON COLUMN TB_DEPARTMENT.DEPARTMENT_NAME IS '학과 이름';
COMMENT ON COLUMN TB_DEPARTMENT.CATEGORY IS '계열';
COMMENT ON COLUMN TB_DEPARTMENT.OPEN_YN IS '개설 여부';
COMMENT ON COLUMN TB_DEPARTMENT.CAPACITY IS '정원';

CREATE TABLE TB_STUDENT
(
    STUDENT_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    STUDENT_NAME VARCHAR2(30) NOT NULL,
    STUDENT_SSN VARCHAR2(14),
    STUDENT_ADDRESS VARCHAR2(100),
    ENTRANCE_DATE DATE,
    ABSENCE_YN CHAR(1) CHECK(ABSENCE_YN IN('Y','N')),
    COACH_PROFESSOR_NO VARCHAR2(10) REFERENCES TB_PROFESSOR(PROFESSOR_NO)
);


CREATE TABLE TB_CLASS
(
    CLASS_NO VARCHAR2(10) PRIMARY KEY,
    DEPARTMENT_NO VARCHAR2(10) REFERENCES TB_DEPARTMENT(DEPARTMENT_NO),
    PREATTENDING_CLASS_NO VARCHAR2(10),
    CLASS_NAME VARCHAR2(30) NOT NULL,
    CLASS_TYPE VARCHAR2(10)
);

CREATE TB_CLASS_PROFESSOR
(
    CLASS_NO VARCHAR2(10) PRIMARY KEY REFERENCES TB_CLASS(CLASS_NO),
    PROFESSOR_NO VARCHAR2(10) PRIMARY KEY REFERENCES TB_PROFESSOR(PROFESSOR_NO)
)

